Commondaysshop/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth import views as auth_views
from django.urls import include
from django.views.static import serve
from django.conf.urls import url
from django.conf import settings
from login import views as v
from django.conf.urls.static import static
from rest_framework.authtoken import  views
from mysite import views as mysiteViews
app_name = "users"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", v.register, name="register"),
    path("", mysiteViews.get_table, name="get_table"),
    path('', include("django.contrib.auth.urls")),
    path('', include('social_django.urls', namespace='social')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(template_name=settings.LOGOUT_REDIRECT_URL),name='logout'),
    path('', include('mysite.urls', namespace='mysite')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'mysite.views.custom_page_not_found_view'
handler500 = 'mysite.views.custom_error_view'
handler403 = 'mysite.views.custom_permission_denied_view'
handler400 = 'mysite.views.custom_bad_request_view'

mysite/urls.py
from django.urls import path
from mysite import views
 
app_name = 'mysite'

urlpatterns = [
    path('tag/<slug:slug>/', views.tagged, name="tagged"),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('product/',views.product, name='product'),
    path('product/detail/<str:product_id>', views.productDetail, name='productDetail'),

    path('product/detail/<str:product_id>/createStock', views.createStock, name='createStock'),
    path('product/detail/<str:product_id>/edit/<str:stock_id>', views.editStock, name='createStock'),
    path('product/detail/<str:product_id>/update/<str:stock_id>', views.updateStock, name='createStock'),

    path('order/', views.order, name='order'),

    path('order/createOrder', views.createOrder, name='createOrder'),
    path('order/edit/<str:order_id>', views.editOrder, name='editOrder'),
    path('order/update/<str:order_id>', views.updateOrder, name='updateOrder'),
    path('order/<str:order_id>/item', views.createItem, name='createItem'),
    path('order/<str:order_id>/item/edit/<str:item_id>', views.editItem, name='editItem'),
    path('order/<str:order_id>/item/delete/<str:item_id>', views.deleteItem, name='deleteItem'),

    path('product/addProduct/', views.createProduct, name='addProduct'),
    path('product/edit/<str:product_id>', views.editProduct, name='editProduct'),
    path('product/update/<str:product_id>', views.updateProduct, name='updateProduct'),
    # path('product/delete/<str:product_id>', views.deleteProduct, name='deleteProduct'),

    path('table/<str:account_id>/', views.table, name='table'),
    path('table/', views.get_table, name='get_table'),
    path('table/<str:account_id>/addStatement', views.createStatement, name='addStatement'),
    path('table/<str:account_id>/delete/<str:statement_id>', views.deleteStatement, name='deleteStatement'),
    path('table/<str:account_id>/edit/<str:statement_id>', views.editStatement, name='editStatement'),
    path('table/<str:account_id>/update/<str:statement_id>', views.updateStatement, name='updateStatement'),

    path('CreateCustomer/', views.create_customer, name='create_customer'),
]

templates/customer/create_customer.html
{% load static %}
{% load widget_tweaks %}
<div style="margin-right: 20px; margin-left: 20px; ">
<form method="POST" data-url="{% url 'mysite:create_customer' %}" class="create-form">
    {% csrf_token %}
        <p hidden>{% render_field form.posted_by class="form-control" %}
        </p>
        
        <div class="modal-header">
            <h5 class="modal-title">Add customer</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>

        <div style="padding-bottom: 20px;"></div>
        <lable style="margin-left: 25px; font-size: 18px;"><b style="color: red;">* </b>Customer name :</lable>
        <div class="wrap-input100 validate-input" style="margin-bottom: 40px;">
            <input class="input100" type="text" name="name" required>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                <i class="fa fa-user" aria-hidden="true"></i>
            </span>
        </div>

        <lable style="margin-left: 25px; font-size: 18px;"><b style="color: red;">* </b>Address :</lable>
        <div class="wrap-input100 validate-input" style="margin-bottom: 40px; ">
            <input class="input100" type="text" name="address" required>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                <i class="fa fa-address-book" aria-hidden="true"></i>
            </span>
        </div>

        <lable style="margin-left: 25px; font-size: 18px;"><b style="color: red;">* </b>Phone number :</lable>
        <div class="wrap-input100 validate-input" style="margin-bottom: 40px; ">
            <input class="input100" type="number" name="telephone" required>
            <span class="focus-input100"></span>
            <span class="symbol-input100">
                <i class="fa fa-phone" aria-hidden="true"></i>
            </span>
        </div>


        <input type="submit" class="btn text-white" name="myButton" value="Submit" style="width: 100%; margin-bottom: 20px;  background-color: #588eaa; ">
        <a style="color: #c80000;">{{ form.errors }}</a>

</form>
</div>